version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
      - database
    networks:
      - app-network

  backend:
    build:
      context: ../corelab-api-challenge
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3333
      APP_KEY: 73rHnSEgVPLfFLpTk8omwzBrMk-c75rX
      DRIVE_DISK: local
      DB_CONNECTION: pg
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: corelab
    depends_on:
      - database
    networks:
      - app-network
    command: sh -c "sleep 5 && node ace migration:run && npm run dev"

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: corelab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
